main/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key= True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    user_name = db.Column(db.String(150))
    phone_number = db.Column(db.String(11), unique=True)
    notes = db.relationship('Note')

class Book(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(50))
    genere = db.Column(db.String(20))
    image = db.Column(db.String(255))
    author = db.Column(db.String(25))
    link = db.Column(db.String(255))

    def __init__(self, title, genere, image_link, author, book_link) -> None:
        self.title = title
        self.genere = genere
        self.image = image_link
        self.author = author
        self.link = book_link

main/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path

db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'ads23'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}' # where to create DataBase
    db.init_app(app)


    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Note
    
    
    with app.app_context():
        db.create_all()

    return app

main/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from sqlalchemy.exc import IntegrityError

auth = Blueprint('auth', __name__)


@auth.route('/sign-up', methods=['GET', 'POST'])
def signup():
    user_name = request.form.get('username')
    email = request.form.get('email')
    password = request.form.get('password')
    password2 = request.form.get('confirm_password')
    phone_number = request.form.get('phone_number')

    try:
        if user_name == 'root':
            flash('Invalid username', category='error')
        elif len(str(password)) < 6:
            flash('Password must be at least 6 characters long', category='error')
        elif password != password2:
            flash('Passwords do not match', category='error')
        elif len(email) < 4:
            flash('Email must be at least 4 characters long', category='error')
        else:
            hashed_password = generate_password_hash(password, method='pbkdf2:sha256')
            new_user = User(user_name=user_name, email=email, password=hashed_password, phone_number=phone_number)
            db.session.add(new_user)
            db.session.commit()
            flash('Account created successfully!', category='success')

    except IntegrityError as e:
        db.session.rollback()  # Roll back the session to prevent partial changes
        flash('An error occurred while creating the account. Please try again later.', category='error')

    return render_template("signup.html")



@auth.route('/login', methods=['GET', 'POST'])
def login():
    data = request.form
    print(data)
    return render_template('login.html')

main/views.py
from flask import Blueprint, render_template, request, redirect, flash, url_for
from .models import Book
from . import db


views = Blueprint('views', __name__)


# root view
@views.route('/')
def home():
    return render_template("home.html")



# Associations view
@views.route('/associations')
def associations():
    return render_template("associations.html")

# Advanture view
@views.route('advanture')
def advanture():
    return render_template("advanture.html")

# project detail view
@views.route('/project')
def project_detail():
    return render_template("project_detail.html")


# library Views

# book shelf
@views.route('/library', methods=['GET'])
def library():
    books = Book.query.all()
    for book in books:
        print(f'Title: {book.title}, Author: {book.author}')
    return render_template("library.html", books=books)


# add book
@views.route('/add-book', methods=['GET', 'POST'])
def add_book():
    if request.method == 'POST':
        title = request.form.get('title')
        author = request.form.get('author')
        genere = request.form.get('genere')
        image = request.form.get('image')
        link = request.form.get('book-link')
        if title:
            new_book = Book(title=title, genere=genere, image_link=image,
                            author=author,
                            book_link=link)
            db.session.add(new_book)
            db.session.commit()
            flash('Book Added Successfully', category="success")
            return redirect(url_for('views.library'))  # Redirect after successful submission
        else:
            flash('Inputs are required!', category='error')

    return render_template('add-book.html')


# delete book
@views.route('/edit-books', methods=['GET', 'POST'])
def delete_book():
    books = Book.query.all()
    if 'delete-btn' in request.form:
        book_id = request.form.get('delete-btn')
        book_to_delete = Book.query.get(book_id)

        db.session.delete(book_to_delete)
        db.session.commit()
        return redirect(url_for('views.library'))
        
    return render_template('delete-book.html', books=books)

main/templates/add-book.html
{% extends "base.html" %}
{% block title %}
  Add Book
{% endblock title %}

{% block body %}
  <div class="container">
    <h1>Add Book</h1>
    <div>
      <a href="/library" class="btn btn-primary">Library</a>
    </div><br>

    <div style="margin-bottom: 3%;">
      <form id="addBookForm" method="post" action="{{ url_for('views.add_book') }}">
        <div class="form-group">
          <label for="title">Title:</label>
          <input type="text" id="title" name="title" class="form-control" required>
        </div>
        <div class="form-group">
          <label for="author">Author:</label>
          <input type="text" id="author" name="author" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="Genere">Genere:</label>
            <input type="text" name="genere" id="genere" class="form-control">
          </div>
        <div class="form-group">
          <label for="image">Image-URL:</label>
          <input type="url" name="image" id="image" class="form-control">
        </div>
        <div class="form-group">
            <label for="image">Book link:</label>
            <input type="url" name="book-link" id="book-link" class="form-control">
          </div>
        <button type="submit" class="btn btn-primary">Add Book</button>
      </form>
    </div>
  </div>
{% endblock body %}

main/templates/advanture.html
{% extends "base.html" %}

main/templates/associations.html
{% extends "base.html" %}

main/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />

    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, viewport-fit=cover maximum-scale=yes"
    />
    <title>{% block title %}title{% endblock title %}</title>
    <!--Styles-->
    <style>
      .icon {
        width: 42px;
        height: 42px;
      }

    </style>
  </head>
  <body style="background-color: #f9a908">
    <!--NavBar-->
    <div class="navbar-fixed-top">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Lub</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="/"
                >Home <span class="sr-only"></span></a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/library">Library</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/sign-up">Sign-up</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/project">Project</a>
            </li>
          </ul>
        </div>
      </nav>
    </div>
    <!--flash-->
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alert-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alert-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <!--Page Body-->
    {% block body %} body {% endblock body %}

    <!--Page Footer-->
    <div>
      <footer class="footer mt-auto py-3" style="background-color: #2b9eb3">
        <h4 class="text-muted" style="text-align: center">lub project</h4>
        <div style="text-align: center;">
          <a href="https://www.github.com/rezamoridi">
            <img
              class="icon"
              src="https://s8.uupload.ir/files/github-mark-white_hd4a.png"
              alt=""
            />
          </a>
          <a href="https://t.me/grandhammer"
            ><img
              src="https://s8.uupload.ir/files/icons8-telegram-48_riae.png"
              alt=""
          /></a>
        </div>
      </footer>
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>

main/templates/delete-book.html
{% extends "base.html" %} {% block title %} delete-book {% endblock title %} {%
block body %}

<style>
  .card {
    width: 33%;
    height: 20%;
  }
</style>
<form action="" method="post">
  {% for book in books %}

  <div class="card">
    <img src="{{ book.image }}" class="card-img-top" alt="Book Image" />
    <div class="card-body">
      <h5 class="card-title">{{ book.title }}</h5>
      <p class="card-text">ID: {{ book.id }}</p>
      <p class="card-text">Author: {{ book.author }}</p>
      <!-- Add additional information or buttons here if needed -->
      <button
        class="delete-button"
        type="submit"
        name="delete-btn"
        id="delete-btn"
        value="{{book.id}}"
      >
        Delete
      </button>
    </div>
  </div>
</form>

{% endfor %} {% endblock body %}

main/templates/home.html
{% extends "base.html" %}
{% block body %}
<style>
  .card {
    margin: 1.5%;
    width: calc(33.33% - 3.5%);
    height: 300px; /* Adjust the height as needed */
    border-radius: 20px;
    overflow: hidden; /* Ensure the image stays within the rounded corners */
    background-color: transparent;
    box-shadow: 5px 7px 5px rgb(100, 74, 6);
  }

  .card img {
    width: 100%; /* Make the image fill the entire width of the card */
    height: 100%; /* Make the image fill the entire height of the card */
    object-fit: cover; /* Ensure the image covers the entire space */
    display: block; /* Ensure the image behaves as a block element */
    border-radius: 20px; /* Apply rounded corners to the image */
  }
  .card-text {
    background-color: rgba(145, 25, 81, 0.401);
    position: absolute; /* Position the text relative to the card */
    bottom: 0; /* Place the text at the bottom of the card */
    left: 0; /* Align the text to the left */
    padding: 10px; /* Add padding to the text */
    color: white; /* Text color */
    font-size: 18px; /* Text size */
    font-weight: bold; /* Text weight */
    width: 100%; /* Full width */
    box-sizing: border-box; /* Include padding in width calculation */
  }
</style>

<div class="d-flex" style="margin-bottom: 60%; margin-top: 45%;">
  <!--card 1-->

  <div class="card">
    <img src="https://cdn.stocksnap.io/img-thumbs/960w/old-books_14QY2T9UPC.jpg" alt="" />
    <a href="/library"><div class="card-text">Library</div></a>
  </div>

  <!--card 2-->

  <div class="card">
    <img src="https://cdn.stocksnap.io/img-thumbs/280h/colorful-buildings_BYZQF9POPZ.jpg" alt="" />
    <a href="/associations"><div class="card-text">Association</div></a>
  </div>

  <!--card 3-->

  <div class="card">
    <img src="https://cdn.stocksnap.io/img-thumbs/960w/rural-road_BSO0DUT9AM.jpg" alt="" />
    <a href="/advanture"><div class="card-text">Advanture</div></a>
  </div>
</div>

{% endblock body %}
{% block title %} Home {% endblock title %}

main/templates/library.html
{% extends "base.html" %} {% block body %}
<style>
.col-md-4{
  filter: drop-shadow(0px 0px 3px crimson);
}

</style>

<div class="container d-flex" style="border-radius: 10px; background-color: rgba(0, 0, 0, 0.187); margin-top: 3%; margin-bottom: 3%;">
  <a style="margin: auto;" href="/add-book"><button type="button" class="btn btn-success">Add Book</button></a>
  <a style="margin: auto;" href="/edit-books"><button type="button" class="btn btn-light">Edit Books</button></a>
</div>

<div class="container">
  <div class="row">
    {% for book in books %}
      <div class="col-md-4 mb-4">
        <div class="card">
          <a href="{{ book.link }}">
            <img src="{{ book.image }}" class="card-img-top" alt="Book Image">
          </a>
          <div class="card-body">
            <h5 class="card-title">{{ book.title }}</h5>
            <p class="card-text">{{ book.author }}</p>
            <p class="card-text text-muted">Genre: {{ book.genere }}</p>
            <a href="{{ book.link }}" class="btn btn-primary">Read More</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>

  {% endblock body %} {% block title %} library {% endblock title
  %}library

main/templates/login.html
{% extends "base.html" %} {% block body %}
<div
  class="container"
  style="
    margin-top: 10%;
    text-align: center;
    background-color: #0fafdc52;
    border-radius: 1%;
  "
>
  <h2>Login</h2>
  <form action="#" method="post">
    <label for="username">Username:</label><br />
    <input type="text" id="username" name="username" required /><br />

    <label for="password">Password:</label><br />
    <input type="password" id="password" name="password" required /><br />



    <input class="btn btn-light" type="submit" value="login" style="margin-top: 10%;" />
  </form>

  <div style="text-align: center; margin-top: 10%; margin-top: 10%">
    <a href="/sign-up">
      <button class="btn btn-primary" style="margin-bottom: 10%;" type="button">Sign-up</button>
    </a>
  </div>
</div>
{% endblock body %} {% block title %}
  login
{% endblock title %}login

main/templates/project_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project</title>
</head>
<style>
    .body{
            background-size: cover; /* Cover the entire background */
            background-position: center; /* Center the image */
            background-attachment: fixed; /* Fix the image in place */
            /* Optionally, you can add more styles like background-repeat, etc. */
        }
</style>
<body style="background-image: url(https://unsplash.com/photos/brown-rock-formation-under-blue-sky-CSpjU6hYo_0);">

    
</body>
</html>

main/templates/signup.html
{% extends "base.html" %} {% block body %}

<div
  class="container"
  style="
    margin-top: 10%;
    text-align: center;
    background-color: #0fafdc52;
    border-radius: 1%;
  "
>
  <h2>Sign Up</h2>
  <form action="#" method="post">
    <label for="username">Username:</label><br />
    <input type="text" id="username" name="username" required /><br />

    <label for="email">Email:</label><br />
    <input type="email" id="email" name="email" required /><br />

    <label for="password">Password:</label><br />
    <input type="password" id="password" name="password" required /><br />

    <label for="confirm_password">Confirm Password:</label><br />
    <input
      type="password"
      id="confirm_password"
      name="confirm_password"
      required
    /><br />

    <label for="phone-number">Phone Number:</label><br />
    <input type="tel" name="phone_number" id="phone_number" required /><br />

    <input class="btn btn-light" type="submit" value="Sign Up" style="margin-top: 10%;" />
  </form>

  <div style="text-align: center; margin-top: 10%; margin-top: 10%">
    <a href="/login">
      <button class="btn btn-primary" style="margin-bottom: 10%;" type="button">login</button>
    </a>
  </div>
</div>
{% endblock body %} {% block title %} authentication {% endblock title %}